import React,{useState} from 'react'
import TexteSelectDepartamento from './TexteSelectDepartamento'
function TexteSelectMunicipio() {
  const [selectedCity, setSelectCity]=useState('SELECCIONE')
  const options={
    'SELECCIONE':['Selecione su departamento'],
    'BENI':['Selecione su municipio','BAURES','EXALTACION','GUAYARAMERÍN','HUACARAJE','LORETO','MAGDALENA','PUERTO SILES','REYES','RIBERALTA','RURRENABAQUE','SAN ANDRÉS','SAN BORJA','SAN IGNACIO','SAN JAVIER','SAN JOAQUÍN','SAN RAMÓN','SANTA ANA DE YACUMA','SANTA ROSA','TRINIDAD',],
    'CHUQUISACA':['Selecione su municipio','CAMARGO','CULPINA','EL VILLAR','HUACAYA','ICLA (R.MUJIA)','INCAHUASI','LAS CARRERAS','MACHARETI','MONTEAGUDO','PADILLA','POROMA','PRESTO','SAN LUCAS','SAN PABLO DE HUACARETA','SOPACHUY','SUCRE','TARABUCO','TARVITA (VILLA ARIAS)','TOMINA','VILLA ABECIA','VILLA ALCALÁ','VILLA AZURDUY','VILLA CHARCAS','VILLA MOJOCOYA','VILLA SERRANO','VILLA VACA GUZMÁN (MUYUPAMPA)','YAMPARÁEZ','YOTALA','ZUDAÑEZ',],
    'COCHABAMBA':['Selecione su municipio','AIQUILE','ALALAY','ANZALDO','ARANI','ARBIETO','ARQUE','BOLIVAR','CAPINOTA','CHIMORE','CLIZA','COCAPATA','COCHABAMBA','COLCAPIRHUA','COLOMI','CUCHUMUELA (V. G.VILLARROEL)','ENTRE RIOS (BULO BULO)','INDEPENDENCIA','MIZQUE','MOROCHATA','OMEREQUE','PASORAPA','POCONA','POJO','PUERTO VILLARROEL','PUNATA','QUILLACOLLO','SACABA','SACABAMBA','SAN BENITO','SANTIBAÑEZ','SHINAHOTA','SICAYA','SIPE SIPE','TACACHI','TACOPAYA','TAPACARÍ','TARATA','TIO- RAQAYPAMPA','TIQUIPAYA','TIRAQUE','TOCO','TOLATA','TOTORA','VACAS','VILA VILA','VILLA RIVERO','VILLA TUNARI','VINTO',],
    'LA PAZ':['Selecione su municipio','ACHACACHI','ACHOCALLA','ALTO BENI','ANCORAIMES','APOLO','AUCAPATA','AYATA','AYO AYO','BATALLAS','CAIROMA','CAJUATA','CALACOTO','CALAMARCA','CAQUIAVIRI','CARANAVI','CATACORA','CHACARILLA','CHARAÑA','CHARAZANI (GRAL.PEREZ)','CHUA COCANI','CHULUMANI','CHUMA','COLLANA','COLQUENCHA','COLQUIRI','COMANCHE','COMBAYA','COPACABANA','CORIPATA','CORO CORO','COROICO','CURVA','DESAGUADERO','EL ALTO','ESCOMA','GUANAY','GUAQUI','HUARINA','HUATAJATA','HUMANATA','ICHOCA','INQUISIVI','IRUPANA','IXIAMAS','JESÚS DE MACHACA','LA ASUNTA','LAJA','LICOMA (VILLA LIBERTAD)','LURIBAY','MALLA','MAPIRI','MECAPACA','MOCOMOCO','NAZACARA DE PACAJES','NUESTRA SEÑORA DE LA PAZ','PALCA','PALOS BLANCOS','PAPEL PAMPA','PATACAMAYA','PELECHUCO','PUCARANI','PUERTO ACOSTA','PUERTO CARABUCO','PUERTO PEREZ','QUIABAYA','QUIME','SAN ANDRÉS DE MACHACA','SAN BUENAVENTURA','SAN PEDRO DE CURAHUARA','SAN PEDRO DE TIQUINA','SANTIAGO DE CALLAPA','SANTIAGO DE HUATA','SANTIAGO DE MACHACA','SAPAHAQUI','SICA SICA','SORATA','TACACOMA','TARACO','TEOPONTE','TIAHUANACU','TIPUANI','TITO YUPANKI','UMALA','VIACHA','WALDO BALLIVIAN','YACO','YANACACHI',],
    'ORURO':['Selecione su municipio','ANTEQUERA (BOLIVAR)','BELÉN DE ANDAMARCA','CARACOLLO','CARANGAS','CHALLAPATA','CHOQUECOTA','COIPASA','CORQUE','CRUZ DE MACHACAMARCA','CURAHUARA DE CARANGAS','EL CHORO','ESCARA','ESMERALDA','EUCALIPTUS','HUACHACALLA','LA RIVERA','MACHACAMARCA','ORURO','PAMPA AULLAGAS','PARIA','PAZÑA','POOPÓ','SABAYA','SALINAS DE GARCI MENDOZA','SAN PEDRO DE TOTORA','SANTIAGO DE ANDAMARCA','SANTIAGO DE HUARI','SANTIAGO DE HUAYLLAMARCA','SANTUARIO DE QUILLACAS','TODOS SANTOS','TOLEDO','TURCO','URU CHIPAYA','VILLA HUANUNI','YUNGUYO DEL LITORAL *',],
    'PANDO':['Selecione su municipio','BELLA FLOR','BOLPEBRA (MUKDEN)','COBIJA','EL SENA','FILADELFIA','INGAVI','NUEVO MANOA (NUEVA ESPERANZA)','PORVENIR','PUERTO GONZALES MORENO','PUERTO RICO','SAN LORENZO','SAN PEDRO (CONQUISTA)','SANTA ROSA DEL ABUNÁ','SANTOS MERCADO','VILLA NUEVA (LOMA ALTA)',],
    'POTOSI':['Selecione su municipio','ACASIO','ARAMPAMPA','ATOCHA','BELÉN DE URMIRI','BETANZOS','CAIZA "D"','CARIPUYO','CHAQUI','CHAYANTA','CHUQUIHUTA','CKOCHAS','COLCHA"K" (V.MARTIN)','COLQUECHACA','COTAGAITA','LLALLAGUA','LLICA','MOJINETE','OCURI','POCOATA','PORCO','POTOSÍ','PUNA','RAVELO','SACACA','SAN AGUSTÍN','SAN ANTONIO DE ESMORUCO','SAN PABLO DE LIPEZ','SAN PEDRO DE BUENA VISTA','SAN PEDRO DE MACHA','SAN PEDRO DE QUEMES','TACOBAMBA','TAHUA','TINGUIPAYA','TOMAVE','TORO TORO','TUPIZA','UNCÍA','UYUNI (THOLA PAMPA)','VILLAZÓN','VITICHI','YOCALLA',],
    'SANTA CRUZ':['Selecione su municipio','ASCENCIÓN DE GUARAYOS','BOYUIBE','BUENA VISTA','CABEZAS','CAMIRI','CARMEN RIVERO TORREZ','CHARAGUA IYAMBAE','COLPA BELGICA','COMARAPA','CONCEPCIÓN','COTOCA','CUATRO CAÑADAS','CUEVO','EL PUENTE','EL TORNO','FERNANDEZ ALONSO','GENERAL SAAVEDRA','KEREIMBA IYAMBAE (GUTIÉRREZ)','LA GUARDIA','LAGUNILLAS','MAIRANA','MINEROS','MONTERO','MORO MORO','OKINAWA UNO','PAILÓN','PAMPA GRANDE','PORONGO (AYACUCHO)','PORTACHUELO','POSTRER VALLE','PUCARA','PUERTO QUIJARRO','PUERTO SUAREZ','QUIRUSILLAS','ROBORE','SAIPINA','SAMAIPATA','SAN ANTONIO DE LOMERIO','SAN CARLOS','SAN IGNACIO DE VELASCO','SAN JAVIER','SAN JOSE DE CHIQUITOS','SAN JUAN','SAN JULIÁN','SAN MATÍAS','SAN MIGUEL DE VELASCO','SAN PEDRO','SAN RAFAEL','SAN RAMÓN','SANTA CRUZ DE LA SIERRA','SANTA ROSA DEL SARA','TRIGAL','URUBICHA','VALLEGRANDE','WARNES','YAPACANÍ',],
    'TARIJA':['Selecione su municipio','BERMEJO','CARAPARÍ','ENTRE RIOS (LA MORETA)','PADCAYA','TARIJA','TOMAYAPO (EL PUENTE)','URIONDO','VILLA SAN LORENZO','VILLAMONTES','YACUIBA','YUNCHARA',]
  }
  const handleCityChange=(city)=>{
    setSelectCity(city);
  }
  return (
    <div>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexDirection:'column'}}>
      <TexteSelectDepartamento defaultOption={selectedCity} onChange={handleCityChange}/>

      </div>
      <div style={{width:"100%",display:'flex',marginTop:"10px"}}>
        <p style={{width:"40%"}}>Municipio:</p>
        <select name="Municipio" id="municipio" style={{backgroundColor:'white',width:"60%",border:"black solid",height:"38px"}}>
            {options[selectedCity].map((option, index)=>(
              <option key={index} value={option}>{option}</option>
            ))}
        </select>
      </div>
    </div>
  )
}

export default TexteSelectMunicipio
